name: 'Next.js Bundle Analysis'

on:
  pull_request:
  push:
    branches:
      # change this if your default branch is named differently
      - main
  workflow_dispatch:

jobs:
  analyze:
    uses: hashicorp/nextjs-bundle-analysis/.github/workflows/analyze.yml@v0.5.0
    with:
      node-version: 24
      package-manager: pnpm
    #   working-directory: ./
    #   build-output-directory: .next
    #   build-command: ./node_modules/.bin/next build