name: Lighthouse
on:
  pull_request:

permissions:
  contents: read

jobs:
  lhci:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      BASE_URL: 'http://localhost:3000'
      URLS: |
        '$BASE_URL/en'
        '$BASE_URL/de'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup base environment
        uses: ./.github/actions/build-dependency

      - name: Build & start
        run: pnpm run build && pnpm run start & npx wait-on@latest $URL_DOMAIN

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: '$URLS'
          configPath: './.github/lighthouse/lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true
